#This is a job file:
#it defines groups of atoms used in the analysis
#in this case one group should define the solute
#another group should define the solvent
[static_groups]         3
#static group 0
name                    solute-H
chain(s)                A B
residue(s)              * 
atom(s)                 !H !H*
residue_number(s)       *
residue_range           *
atom_number(s)          *
atom_range              *
#static group 1
name                    solute
chain(s)                A B
residue(s)              *
atom(s)                 *
residue_number(s)       *
residue_range           *
atom_number(s)          *
atom_range              *
#static group 2
name                    water
chain(s)                *
residue(s)              SOL
atom(s)                 *
residue_number(s)       *
residue_range           *
atom_number(s)          *
atom_range              *
#feature to select groups of atoms/molecules by distance criteria
#not used/necessary here
[dynamic_groups]        0
#feature to combine previously defined groups
#not used/necessary here
[combination_groups]     0
